### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by Sailren** [modmuss50/JSON-Destroyer#10]
this crash happens during startup, there is no standalone jsondestroyer in my mods folder, so this cant be the case

http://paste.ubuntu.com/16277777/

these are the mods i have, which are from you and/or your team

techreborn{1.0.6.215} [TechReborn] (TechReborn-1.9-1.0.6.215-universal.jar) 

reborncore{2.1.0.61} [RebornCore] (RebornCore-1.9-2.1.0.61-universal.jar) 

additionally i have this: Tesla{1.0.1.9} [TESLA] (Tesla-1.9-1.0.1.21.jar)  installed

still crashing with reborncore{2.1.0.61} [RebornCore] (RebornCore-1.9-2.1.0.61-universal.jar)

**Comment by Sailren** [comment]
lemme test reborncore 61

**Comment by modmuss50** [comment]
Fixed here: https://github.com/modmuss50/JSON-Destroyer/commit/977f5ea977da85c3df00197c437011efa0dce811

**Comment by modmuss50** [comment]
Update reborn core

**Comment by modmuss50** [comment]
it will be fixed with build 62
