### ISSUE TITLE
Let getTextureName have access to the ItemStack

### ISSUE THREAD

**Issue by ProfessorProspector** [modmuss50/JSON-Destroyer#3]
Currently all getTextureName can do is get the damage. Would be nice to also be able to get the stack.

**Comment by modmuss50** [comment]
What do you actullay need the stack for?

**Comment by ProfessorProspector** [comment]
I'd like to return a different texture based on an items every level. (Could also be used for other tags)

**Comment by modmuss50** [comment]
The models/textures can only be set based on the damage, that is possible without the stack. You would have to use the damage to store the power of the item. Its not something that is possible with the current minecraft model system.

**Comment by ProfessorProspector** [comment]
Hmm yep I derped. That makes sense. Thanks anyway
