### ISSUE TITLE
Pressing F3-S to reload assets messes up items using json destroyer most of the time

### ISSUE THREAD

**Issue by ProfessorProspector** [modmuss50/JSON-Destroyer#5]
Specifically, sometimes it gives items random textures, doesn't give the item the proper model (noticeable when the item is held in hand or dropped in ground) and sometimes it just doesn't give some items models or textures.

**Comment by modmuss50** [comment]
Whats the diffrence between F3-S and F3-T, I use F3-T?

**Comment by ProfessorProspector** [comment]
Hmm I don't know. I think F3+s does sounds too. Guess I'll use T from now on

**Comment by modmuss50** [comment]
I will take a look into it anyway
