### ISSUE TITLE
Change transform method to use MapWrapper

### ISSUE THREAD

**Issue by adudney** [modmuss50/JSON-Destroyer#7]
https://github.com/modmuss50/JSON-Destroyer/blob/1.9/src/main/java/me/modmuss50/jsonDestroyer/client/ModelGenerator.java#L377

The method can be replaced with "return IPerspectiveAwareModel.MapWrapper.handlePerspective(this, transforms, cameraTransformType);" as shown here: https://github.com/SlimeKnights/TinkersConstruct/blob/129dbbe84db272a131f962442d58dadd72ff786b/src/main/java/slimeknights/tconstruct/library/client/model/BakedMaterialModel.java#L68

And here: https://github.com/MinecraftForge/MinecraftForge/search?utf8=✓&q=MapWrapper

This may fix https://github.com/TechReborn/RebornCore/issues/12 but I'm not certain.

**Comment by modmuss50** [comment]
thanks for that, I did plan to use this.
